// This file is part of midnightntwrk/example-counter.
// Copyright (C) 2025 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * This file is the main driver for the P2P ZK Wordle game.
 * The entry point is the run function, at the end of the file.
 * We expect the startup files (testnet-remote.ts, standalone.ts, etc.) to
 * call run with some specific configuration that sets the network addresses
 * of the servers this file relies on.
 */

// Wallet seed: 8dd96c613b92a1ced03ac5e71a039d4447cfe84928864fc38260b28cd30378c2

import { createInterface, type Interface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { WebSocket } from 'ws';
import {
  type WordleProviders,
  WordleAPI,
  utils,
  type WordleDerivedState,
  type DeployedWordleContract,
  type PrivateStateId,
  bboardPrivateStateKey,
  GameState,
  type Word,
  type GuessResult,
} from '../../api/src/index';
import { ledger, type Ledger } from '../../contract/src/managed/bboard/contract/index.cjs';
import {
  type BalancedTransaction,
  createBalancedTx,
  type MidnightProvider,
  type UnbalancedTransaction,
  type WalletProvider,
} from '@midnight-ntwrk/midnight-js-types';
import { type Wallet } from '@midnight-ntwrk/wallet-api';
import * as Rx from 'rxjs';
import { type CoinInfo, nativeToken, Transaction, type TransactionId } from '@midnight-ntwrk/ledger';
import { Transaction as ZswapTransaction } from '@midnight-ntwrk/zswap';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { type Resource, WalletBuilder } from '@midnight-ntwrk/wallet';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { type Logger } from 'pino';
import { type Config, StandaloneConfig } from './config.js';
import type { StartedDockerComposeEnvironment, DockerComposeEnvironment } from 'testcontainers';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { type ContractAddress } from '@midnight-ntwrk/compact-runtime';
import { toHex, assertIsContractAddress } from '@midnight-ntwrk/midnight-js-utils';
import { getLedgerNetworkId, getZswapNetworkId } from '@midnight-ntwrk/midnight-js-network-id';

// @ts-expect-error: It's needed to enable WebSocket usage through apollo
globalThis.WebSocket = WebSocket;

/* **********************************************************************
 * getWordleLedgerState: a helper that queries the current state of
 * the data on the ledger, for a specific P2P Wordle contract.
 * Note that the Ledger type returned here is not some generic,
 * abstract ledger object, but specifically the type generated by
 * the Compact compiler to correspond to the ledger declaration
 * in the Wordle contract.
 */

export const getWordleLedgerState = async (
  providers: WordleProviders,
  contractAddress: ContractAddress,
): Promise<Ledger | null> => {
  assertIsContractAddress(contractAddress);
  const contractState = await providers.publicDataProvider.queryContractState(contractAddress);
  return contractState != null ? ledger(contractState.data) : null;
};

/* **********************************************************************
 * deployOrJoin: returns a contract, by prompting the user about
 * whether to deploy a new one or join an existing one and then
 * calling the appropriate helper.
 */

const DEPLOY_OR_JOIN_QUESTION = `
You can do one of the following:
  1. Deploy a new P2P Wordle game contract
  2. Join an existing P2P Wordle game contract  
  3. Exit
Which would you like to do? `;

const deployOrJoin = async (providers: WordleProviders, rli: Interface, logger: Logger): Promise<WordleAPI | null> => {
  let api: WordleAPI | null = null;

  while (true) {
    const choice = await rli.question(DEPLOY_OR_JOIN_QUESTION);
    switch (choice) {
      case '1':
        api = await WordleAPI.deploy(providers, logger);
        logger.info(`Deployed Wordle contract at address: ${api.deployedContractAddress}`);
        return api;
      case '2':
        api = await WordleAPI.join(providers, await rli.question('What is the contract address (in hex)? '), logger);
        logger.info(`Joined Wordle contract at address: ${api.deployedContractAddress}`);
        return api;
      case '3':
        logger.info('Exiting...');
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * displayLedgerState: shows the values of each of the fields declared
 * by the contract to be in the ledger state of the P2P Wordle game.
 */

const displayLedgerState = async (
  providers: WordleProviders,
  deployedWordleContract: DeployedWordleContract,
  logger: Logger,
): Promise<void> => {
  const contractAddress = deployedWordleContract.deployTxData.public.contractAddress;
  const ledgerState = await getWordleLedgerState(providers, contractAddress);
  if (ledgerState === null) {
    logger.info(`There is no Wordle contract deployed at ${contractAddress}`);
  } else {
    const gameStateNames = [
      'waiting_p1', 
      'waiting_p2', 
      'p1_guess_turn', 
      'p2_verify_turn', 
      'p2_guess_turn', 
      'p1_verify_turn', 
      'p1_wins', 
      'p2_wins', 
      'draw'
    ];
    logger.info(`Game state: ${gameStateNames[ledgerState.game_state] || 'unknown'}`);
    logger.info(`P1 joined: ${ledgerState.p1.is_some ? 'Yes' : 'No'}`);
    logger.info(`P2 joined: ${ledgerState.p2.is_some ? 'Yes' : 'No'}`);
    logger.info(`P1 guess count: ${ledgerState.p1_guess_count}`);
    logger.info(`P2 guess count: ${ledgerState.p2_guess_count}`);
    
    if (ledgerState.last_guess_result.is_some) {
      const result = ledgerState.last_guess_result.value;
      logger.info(`Last guess result: [${result.first_letter_result}, ${result.second_letter_result}, ${result.third_letter_result}, ${result.fourth_letter_result}, ${result.fifth_letter_result}]`);
    } else {
      logger.info(`Last guess result: None`);
    }
  }
};

/* **********************************************************************
 * displayPrivateState: shows the hex-formatted value of the secret key,
 * salt, and the player's chosen word.
 */

const displayPrivateState = async (providers: WordleProviders, logger: Logger): Promise<void> => {
  const privateState = await providers.privateStateProvider.get(bboardPrivateStateKey);
  if (privateState === null) {
    logger.info(`There is no existing Wordle private state`);
  } else {
    logger.info(`Current secret key: ${toHex(privateState.secretKey)}`);
    logger.info(`Current salt: ${toHex(privateState.salt)}`);
    logger.info(`Current word: ${new TextDecoder().decode(privateState.word).slice(0, 5)}`);
    
    // Compute and display the player identity for debugging
    const { pureCircuits } = await import('../../contract/src/managed/bboard/contract/index.cjs');
    const playerIdentity = pureCircuits.public_key(privateState.secretKey);
    logger.info(`Your computed identity: ${toHex(playerIdentity)}`);
  }
};

/* **********************************************************************
 * displayDerivedState: shows the values of derived state which is made
 * by combining the ledger state with private state. In this example, the
 * derived state determines the player's role, whose turn it is, and
 * whether they can take actions in the game.
 */

const displayDerivedState = (gameState: WordleDerivedState | undefined, logger: Logger) => {
  if (gameState === undefined) {
    logger.info(`No Wordle game state currently available`);
  } else {
    const gameStateNames = [
      'waiting_p1', 
      'waiting_p2', 
      'p1_guess_turn', 
      'p2_verify_turn', 
      'p2_guess_turn', 
      'p1_verify_turn', 
      'p1_wins', 
      'p2_wins', 
      'draw'
    ];
    logger.info(`Game State: ${gameStateNames[gameState.gameState] || 'unknown'}`);
    logger.info(`Your role: ${gameState.playerRole}`);
    logger.info(`Is Player 1: ${gameState.isPlayer1}`);
    logger.info(`Is Player 2: ${gameState.isPlayer2}`);
    logger.info(`Is your turn: ${gameState.isMyTurn ? 'Yes' : 'No'}`);
    logger.info(`Can join: ${gameState.canJoin ? 'Yes' : 'No'}`);
    logger.info(`P1 guess count: ${gameState.p1GuessCount}`);
    logger.info(`P2 guess count: ${gameState.p2GuessCount}`);
    
    // Debug info
    if (gameState.p1) {
      logger.info(`P1 identity: ${toHex(gameState.p1)}`);
    }
    if (gameState.p2) {
      logger.info(`P2 identity: ${toHex(gameState.p2)}`);
    }
    
    if (gameState.lastGuessResult) {
      const result = gameState.lastGuessResult;
      logger.info(`Last guess result: [${result.first_letter_result}, ${result.second_letter_result}, ${result.third_letter_result}, ${result.fourth_letter_result}, ${result.fifth_letter_result}]`);
    }
  }
};

/* **********************************************************************
 * mainLoop: the main interactive menu of the P2P Wordle CLI.
 * Before starting the loop, the user is prompted to deploy a new
 * contract or join an existing one.
 */

const MAIN_LOOP_QUESTION = `
You can do one of the following:
  1. Join as Player 1 (with your word)
  2. Join as Player 2 (with your word)  
  3. Make a guess at opponent's word
  4. Verify Player 1's guess (Player 2 only)
  5. Verify Player 2's guess (Player 1 only)
  6. Display the current ledger state (known by everyone)
  7. Display the current private state (known only to this DApp instance)
  8. Display the current derived state (known only to this DApp instance)
  9. Exit
Which would you like to do? `;

const mainLoop = async (providers: WordleProviders, rli: Interface, logger: Logger): Promise<void> => {
  const wordleApi = await deployOrJoin(providers, rli, logger);
  if (wordleApi === null) {
    return;
  }
  let currentState: WordleDerivedState | undefined;
  const stateObserver = {
    next: (state: WordleDerivedState) => (currentState = state),
  };
  const subscription = wordleApi.state$.subscribe(stateObserver);
  try {
    while (true) {
      const choice = await rli.question(MAIN_LOOP_QUESTION);
      switch (choice) {
        case '1': {
          const word = await rli.question(`What 5-letter word do you want to use? `);
          if (word.length !== 5) {
            logger.error('Word must be exactly 5 letters!');
            break;
          }
          try {
            await wordleApi.joinAsPlayer1(word.toUpperCase());
            logger.info('Successfully joined as Player 1!');
          } catch (error) {
            logger.error(`Failed to join as Player 1: ${error}`);
          }
          break;
        }
        case '2': {
          const word = await rli.question(`What 5-letter word do you want to use? `);
          if (word.length !== 5) {
            logger.error('Word must be exactly 5 letters!');
            break;
          }
          try {
            await wordleApi.joinAsPlayer2(word.toUpperCase());
            logger.info('Successfully joined as Player 2!');
          } catch (error) {
            logger.error(`Failed to join as Player 2: ${error}`);
          }
          break;
        }
        case '3': {
          const guess = await rli.question(`What 5-letter word do you want to guess? `);
          if (guess.length !== 5) {
            logger.error('Guess must be exactly 5 letters!');
            break;
          }
          try {
            await wordleApi.makeGuess(guess.toUpperCase());
            logger.info('Guess submitted!');
          } catch (error) {
            logger.error(`Failed to make guess: ${error}`);
          }
          break;
        }
        case '4':
          try {
            await wordleApi.verifyP1Guess();
            logger.info('Player 1\'s guess verified!');
          } catch (error) {
            logger.error(`Failed to verify Player 1's guess: ${error}`);
          }
          break;
        case '5':
          try {
            await wordleApi.verifyP2Guess();
            logger.info('Player 2\'s guess verified!');
          } catch (error) {
            logger.error(`Failed to verify Player 2's guess: ${error}`);
          }
          break;
        case '6':
          await displayLedgerState(providers, wordleApi.deployedContract, logger);
          break;
        case '7':
          await displayPrivateState(providers, logger);
          break;
        case '8':
          displayDerivedState(currentState, logger);
          break;
        case '9':
          logger.info('Exiting...');
          return;
        default:
          logger.error(`Invalid choice: ${choice}`);
      }
    }
  } finally {
    // While we allow errors to bubble up to the 'run' function, we will always need to dispose of the state
    // subscription when we exit.
    subscription.unsubscribe();
  }
};

/* **********************************************************************
 * createWalletAndMidnightProvider: returns an object that
 * satifies both the WalletProvider and MidnightProvider
 * interfaces, both implemented in terms of the given wallet.
 */

const createWalletAndMidnightProvider = async (wallet: Wallet): Promise<WalletProvider & MidnightProvider> => {
  const state = await Rx.firstValueFrom(wallet.state());
  return {
    coinPublicKey: state.coinPublicKey,
    encryptionPublicKey: state.encryptionPublicKey,
    balanceTx(tx: UnbalancedTransaction, newCoins: CoinInfo[]): Promise<BalancedTransaction> {
      return wallet
        .balanceTransaction(
          ZswapTransaction.deserialize(tx.serialize(getLedgerNetworkId()), getZswapNetworkId()),
          newCoins,
        )
        .then((tx) => wallet.proveTransaction(tx))
        .then((zswapTx) => Transaction.deserialize(zswapTx.serialize(getZswapNetworkId()), getLedgerNetworkId()))
        .then(createBalancedTx);
    },
    submitTx(tx: BalancedTransaction): Promise<TransactionId> {
      return wallet.submitTransaction(tx);
    },
  };
};

/* **********************************************************************
 * waitForFunds: wait for tokens to appear in a wallet.
 *
 * This is an interesting example of watching the stream of states
 * coming from the pub-sub indexer.  It watches both
 *  1. how close the state is to present reality and
 *  2. the balance held by the wallet.
 */

const waitForFunds = (wallet: Wallet, logger: Logger) =>
  Rx.firstValueFrom(
    wallet.state().pipe(
      Rx.throttleTime(10_000),
      Rx.tap((state) => {
        const scanned = state.syncProgress?.synced ?? 0n;
        const behind = state.syncProgress?.lag.applyGap.toString() ?? 'unknown number';
        logger.info(`Wallet processed ${scanned} indices, remaining ${behind}`);
      }),
      Rx.filter((state) => {
        // Let's allow progress only if wallet is close enough
        const synced = typeof state.syncProgress?.synced === 'bigint' ? state.syncProgress.synced : 0n;
        const total = typeof state.syncProgress?.lag?.applyGap === 'bigint' ? state.syncProgress.lag.applyGap : 1_000n;
        return total - synced < 100n;
      }),
      Rx.map((s) => s.balances[nativeToken()] ?? 0n),
      Rx.filter((balance) => balance > 0n),
    ),
  );

/* **********************************************************************
 * buildWalletAndWaitForFunds: the main function that creates a wallet
 * and waits for tokens to appear in it.  The various "buildWallet"
 * functions all arrive here after collecting information for the
 * arguments.
 */

const buildWalletAndWaitForFunds = async (
  { indexer, indexerWS, node, proofServer }: Config,
  logger: Logger,
  seed: string,
): Promise<Wallet & Resource> => {
  const wallet = await WalletBuilder.buildFromSeed(
    indexer,
    indexerWS,
    proofServer,
    node,
    seed,
    getZswapNetworkId(),
    'warn',
  );
  wallet.start();
  const state = await Rx.firstValueFrom(wallet.state());
  logger.info(`Your wallet seed is: ${seed}`);
  logger.info(`Your wallet address is: ${state.address}`);
  let balance = state.balances[nativeToken()];
  if (balance === undefined || balance === 0n) {
    logger.info(`Your wallet balance is: 0`);
    logger.info(`Waiting to receive tokens...`);
    balance = await waitForFunds(wallet, logger);
  }
  logger.info(`Your wallet balance is: ${balance}`);
  return wallet;
};

// Generate a random see and create the wallet with that.
const buildFreshWallet = async (config: Config, logger: Logger): Promise<Wallet & Resource> =>
  await buildWalletAndWaitForFunds(config, logger, toHex(utils.randomBytes(32)));

// Prompt for a seed and create the wallet with that.
const buildWalletFromSeed = async (config: Config, rli: Interface, logger: Logger): Promise<Wallet & Resource> => {
  const seed = await rli.question('Enter your wallet seed: ');
  return await buildWalletAndWaitForFunds(config, logger, seed);
};

/* ***********************************************************************
 * This seed gives access to tokens minted in the genesis block of a local development node - only
 * used in standalone networks to build a wallet with initial funds.
 */
const GENESIS_MINT_WALLET_SEED = '0000000000000000000000000000000000000000000000000000000000000001';

/* **********************************************************************
 * buildWallet: unless running in a standalone (offline) mode,
 * prompt the user to tell us whether to create a new wallet
 * or recreate one from a prior seed.
 */

const WALLET_LOOP_QUESTION = `
You can do one of the following:
  1. Build a fresh wallet
  2. Build wallet from a seed
  3. Exit
Which would you like to do? `;

const buildWallet = async (config: Config, rli: Interface, logger: Logger): Promise<(Wallet & Resource) | null> => {
  if (config instanceof StandaloneConfig) {
    return await buildWalletAndWaitForFunds(config, logger, GENESIS_MINT_WALLET_SEED);
  }
  while (true) {
    const choice = await rli.question(WALLET_LOOP_QUESTION);
    switch (choice) {
      case '1':
        return await buildFreshWallet(config, logger);
      case '2':
        return await buildWalletFromSeed(config, rli, logger);
      case '3':
        logger.info('Exiting...');
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

const mapContainerPort = (env: StartedDockerComposeEnvironment, url: string, containerName: string) => {
  const mappedUrl = new URL(url);
  const container = env.getContainer(containerName);

  mappedUrl.port = String(container.getFirstMappedPort());

  return mappedUrl.toString().replace(/\/+$/, '');
};

/* **********************************************************************
 * run: the main entry point that starts the whole bulletin board CLI.
 *
 * If called with a Docker environment argument, the application
 * will wait for Docker to be ready before doing anything else.
 */

export const run = async (config: Config, logger: Logger, dockerEnv?: DockerComposeEnvironment): Promise<void> => {
  const rli = createInterface({ input, output, terminal: true });
  
  // Generate a unique private state store name for this session
  const sessionId = Math.random().toString(36).substring(2, 8);
  const uniquePrivateStateName = `${config.privateStateStoreName}-${sessionId}`;
  logger.info(`Using private state store: ${uniquePrivateStateName}`);
  
  let env;
  if (dockerEnv !== undefined) {
    env = await dockerEnv.up();

    if (config instanceof StandaloneConfig) {
      config.indexer = mapContainerPort(env, config.indexer, 'bboard-indexer');
      config.indexerWS = mapContainerPort(env, config.indexerWS, 'bboard-indexer');
      config.node = mapContainerPort(env, config.node, 'bboard-node');
      config.proofServer = mapContainerPort(env, config.proofServer, 'bboard-proof-server');
    }
  }
  const wallet = await buildWallet(config, rli, logger);
  try {
    if (wallet !== null) {
      const walletAndMidnightProvider = await createWalletAndMidnightProvider(wallet);
      const providers = {
        privateStateProvider: levelPrivateStateProvider<PrivateStateId>({
          privateStateStoreName: uniquePrivateStateName,
        }),
        publicDataProvider: indexerPublicDataProvider(config.indexer, config.indexerWS),
        zkConfigProvider: new NodeZkConfigProvider<'join_p1' | 'join_p2' | 'turn_player1' | 'turn_player2' | 'verify_p1_guess' | 'verify_p2_guess'>(config.zkConfigPath),
        proofProvider: httpClientProofProvider(config.proofServer),
        walletProvider: walletAndMidnightProvider,
        midnightProvider: walletAndMidnightProvider,
      };
      await mainLoop(providers, rli, logger);
    }
  } catch (e) {
    logError(logger, e);
    logger.info('Exiting...');
  } finally {
    try {
      rli.close();
      rli.removeAllListeners();
    } catch (e) {
      logError(logger, e);
    } finally {
      try {
        if (wallet !== null) {
          await wallet.close();
        }
      } catch (e) {
        logError(logger, e);
      } finally {
        try {
          if (env !== undefined) {
            await env.down();
            logger.info('Goodbye');
            process.exit(0);
          }
        } catch (e) {
          logError(logger, e);
        }
      }
    }
  }
};

function logError(logger: Logger, e: unknown) {
  if (e instanceof Error) {
    logger.error(`Found error '${e.message}'`);
    logger.debug(`${e.stack}`);
  } else {
    logger.error(`Found error (unknown type)`);
  }
}
